### ISSUE TITLE
Applications set prototype

### ISSUE THREAD

**Issue by 0xbase12** [nuvla/nuvla#108]
- [x] Apps sets subtype support apps navigation
- [x] Apps sets subtype support add apps modal
- [x] Apps sets detail page with common
- [x] Possibility add remove apps sets title description
- [x] Possibility to select apps for each set
- [x] Reload application sets
- [x] Save applications sets
- [x] Basic form validation support
- [x] Add Apps sets configuration tab
- [x] Show apps sets tabs with each application configuration
- [x] Add version selection for selected apps
- [x] Environment variables support
- [x] Show module not found message or not sufficient right when not all apps are visible to user or have been deleted
- [x] Apps selector should support filter subtypes
- [x] Limit selection of apps to docker or k8s depending on existing apps
- [x] When empty set, ask user if he wants to select k8s apps or docker
- [x] Launch button support

**Comment by 0xbase12** [comment]
- [x] Apps sets subtype support apps navigation
- [x] Apps sets subtype support add apps modal
- [x] Apps sets detail page with common
- [x] Possibility add remove apps sets title description
- [x] Possibility to select apps for each set
- [x] Reload application sets
- [x] Save applications sets
- [x] Basic form validation support
- [x] Add Apps sets configuration tab
- [x] Show apps sets tabs with each application configuration
- [x] Add version selection for selected apps
- [x] Environment variables support
- [x] Show module not found message or not sufficient right when not all apps are visible to user or have been deleted
- [ ] Files support
- [ ] Private registries credentials support
- [ ] Launch button support

**Comment by 0xbase12** [comment]
# Launch button support 

Creation of deployment set from module applications_sets subtype

Store `module` of subtype `applications_sets` in `deployment set` like for `module` is stored/duplicated in `deployment`. Keep a version of it internally or duplicate Apps sets content in deployment set, overwrite env vars in place.

Keep reference to version of Deployment sets version created from. Possible deployments sets table as for deployments tab for module.
