### ISSUE TITLE
deploy Swarm and K8s COE from Nuvla.io

### ISSUE THREAD

**Issue by konstan** [nuvla/nuvla#30]
This is a revival of the work @cjdcordeiro did some time ago for Docker Swarm. (@cjdcordeiro can you please provide pointers to branches/PRs? I did a quick search, but couldn't find them. Thanks.) 

Extensions to that work will be K8s and COE managers installed along the COEs and registered with Nuvla.io.

### Deployment of COEs.

- [x] Deploy Docker Swarm and a cluster manager. Choices for the manager:
  * https://portainer.io
  * https://swarmpit.io
  * ???

- [x] Deploy Kubernetes and a cluster manager. Choices for the manager:
  * https://rancher.com/
  * ???

After the full deployment and registration of COE, provide the following in Nuvla.io
- [x] COE endpoint as IS
- [x] COE admin creds as IS creds
- [x] link to the COE manager and admin creds (consider using IS in the same IS group and IS creds?!)

### docker-machine

For deployment of Docker Swarm use docker-machine (as was done by @cjdcordeiro).

For deployment of Kubernetes use docker-machine with Kubernetes on top. Reuse work done by @konstan for EFCA https://github.com/SixSq/efca-fluxtl/, https://github.com/SixSq/efca-fluxtl/tree/master/infrastructure/K8s-cluster

There is a problem with docker-machine though: last commit is on 2 Sep 2019 and there are 954 issues opened :-/ It's not actively developed and there are a lot of bugs/issues there. Personally lately I had a number of issues with the CLI when working with the clusters.

### Alternative tools for provisioning

List of docker-machine alternatives to consider:

* terraform (pros: reliable, examples exist, actively developed/supported // cons: another DSL to learn, need to develop integration)
* Ansible (pros reliable, we have experience, actively developed/supported // cons: need to develop integration)
* use https://libcloud.apache.org/ and implement a-la SlipStream (pros reliable, we have experience, actively developed/supported // cons: requires development from scratch)

Comment on Ansible integration:
* written in Python,
* writing Ansible modules is straightforward,
* we can have our own `nuvla` module with a set of tasks `nuvla_create_infra`, `nuvla_create_cred` etc.

**Comment by cjdcordeiro** [comment]
previous work is:
 - api-server:master (where the CSP credential schemas are already)
 - api-server:swarm-nodes (https://github.com/nuvla/api-server/tree/swarm-nodes)
 - api-server:job-hooks (with the IS hooks for managing the created machines: https://github.com/nuvla/api-server/tree/swarm-nodes)
 - job:master (already has the jobs for deploying the Docker machines)

**Comment by konstan** [comment]
Implemented. Closing.
