### ISSUE TITLE
add workflow for enforcing default Docker registries and trusted images

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/nuvla#36]
- [x] add image trust check from nuvla (https://github.com/nuvla/job-engine/issues/120)
 - [x] show whether docker images are trusted or not, in the UI (https://github.com/nuvla/ui/issues/415)
 - [x] make sure SixSq's docker authz plugin can be parametrized to fix a constrain requests to a registry (https://github.com/nuvla/nuvla/issues/35)
 - [x] document the installation of the docker authz plugin (https://github.com/nuvla/documentation/issues/50)
 - [x] add reporting of installed docker plugins to nb engine's agent (https://github.com/nuvlabox/agent/issues/39)
 - [x] add new attr to nb status for docker plugins (https://github.com/nuvla/api-server/issues/384)
 - [x] build plugins for multiple archs (https://github.com/orgs/nuvla/projects/1#card-45071298)

**Comment by cjdcordeiro** [comment]
@schaubl please let me know once the missing 2 are finished so that we can plan a full demo
