### ISSUE TITLE
implement bulk management for a collection of deployments

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/nuvla#38]
Summary of actions:
 - [x] nuvla/ui#459 - implement guided filters
 - [ ] nuvla/ui#473 - improve the UI to show all ISs where a deployment is running
 - [x] nuvla/ui#474 - apply filters to dashboard page
 - [ ] nuvla/ui#475 - implement bulk actions for the selected filters

_edited by @schaubl_

**Comment by 0xbase12** [comment]
Functionality will be implemented in deployment set
