### ISSUE TITLE
design and implement the workflows for Alice vs Clara module updates and update notification

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/nuvla#39]
Summary of actions:
 - add "Publish" state for modules
 - only published modules will be notified to Alice as candidates for update 
 - Alice can still force updates and select specific version, even if not published 

_edit: added by @schaubl_ 
Sub-issues:
- [x] nuvla/api-server#406 - Add "published" state for modules
- [ ] nuvla/ui#476 - Take into account the "published" state of modules (components/applications)
- [ ] nuvla/nuvla#41 - As a User, I can subscribe to notifications on new versions of published modules

**Comment by mebster** [comment]
Add publish attribute to versions and indicate with a similar attribute on module that it contains at least one published version. 

Add publish action on a version, without increasing the version.

**Comment by mebster** [comment]
Now duplicates: https://github.com/SixSq/tasklist/issues/2622
