### ISSUE TITLE
implement the UPDATE workflow for active deployments

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/nuvla#40]
Summary of actions:
 - Button restart becomes: restart/update, depending on deployment state
 - fetch button moves inside the restart/update modal, as a dropdown list of the available module versions we can use for the update
 - force updates without changes can also happen, implying that there might be an upstream update to the Docker image tag being used (need to force image pull when updating the deployment on the IS)

This action is to be applied in bulk (#38 )

_Edit: added by @schaubl_
Sub-issues:
- [x] nuvla/ui#470 - deployment: enhance the launch dialog to support the update feature ***
- [x] nuvla/ui#471 - deployment launch dialog: add a step to be able to select the version of the module to run ***
- [ ] nuvla/ui#472 - allow to get a diff from 2 versions of a module (component or application) *
- [x] nuvla/api-server#403 - deployment: enhance the fetch feature to be able to fetch a specific version **
- [x] nuvla/api-server#410 -  deployment: implement the "update" action
- [x] nuvla/job-engine#128 - create the job update_deployment ***
and proposed priorities by @mebster

**Comment by schaubl** [comment]
Sub-issues:
- nuvla/ui#470 - deployment: enhance the launch dialog to support the update feature
- nuvla/ui#471 - deployment launch dialog: add a step to be able to select the version of the module to run
- nuvla/ui#472 - allow to get a diff from 2 versions of a module (component or application)
- nuvla/api-server#403 - deployment: enhance the fetch feature to be able to fetch a specific version
- nuvla/job-engine#128 - create the job update_deployment

**Comment by mebster** [comment]
Do we need a separate issue for nuvla/ui#470 on a list of NBs? Since we should already not be able to change the IS, is it "just" a case of being able to apply to a list?  But then there's the issue of reducing the values for all "parameters" (e.g. ENV, files) and either not showing them or showing only the ones that are identical for all?

**Comment by schaubl** [comment]
> Do we need a separate issue for [nuvla/ui#470](https://github.com/nuvla/ui/issues/470) on a list of NBs? Since we should already not be able to change the IS, is it "just" a case of being able to apply to a list? But then there's the issue of reducing the values for all "parameters" (e.g. ENV, files) and either not showing them or showing only the ones that are identical for all?

This should probably go into #38 (implement bulk management for a collection of deployments).
This issue is about the update of a deployment triggered from within a deployment.
Doing it with a bulk of deployment will probably have to be triggered from the "list of deployments" of from the module itself.
