### ISSUE TITLE
implement pull-mode job execution support in Nuvla

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/nuvla#43]
wiki at https://github.com/SixSq/tasklist/wiki/NuvlaBox-Workloads-in-Pull-mode

By order of implementation:
 - [x] add pull-mode attributes to job resource (https://github.com/nuvla/api-server/issues/412)
 - [x] add pull-mode attributes to deployment (https://github.com/nuvla/api-server/issues/413)
 - [x] provide more details and enforce credential availability, based on credential check (https://github.com/nuvla/job-engine/issues/144)
 - [x] add capabilities map attribute to infrastructure-services (https://github.com/nuvla/api-server/issues/429)
 - [x] add capabilities map attribute to NuvlaBox (https://github.com/nuvla/api-server/issues/430)
 - [x] do not queue jobs that have provisioning-mode=pull (https://github.com/nuvla/job-engine/issues/130)
 - [x] add job execution conditional for "mixed" provisioning-mode jobs (https://github.com/nuvla/job-engine/issues/131)
 - [x] compile a "pull-mode response" for all NuvlaBox status updates (telemetry) (https://github.com/nuvla/api-server/issues/414)
 - [x] Implement get-context action on jobs (https://github.com/nuvla/api-server/issues/436)
 - [x] Use get-context job action to get access to needed documents from api-server (https://github.com/nuvla/job-engine/issues/150)
 - [x] Add ability to start the job-executor for a specific pull-mode job execution (instead of zookeeper) (https://github.com/nuvla/job-engine/issues/133)
 - [x] added business logic to job engine to make sure it only runs jobs according to its version (https://github.com/nuvla/job-engine/issues/134)
 - [x] when running a pull mode job, the job-engine(-lite) must keep the necessary apikey on disk (https://github.com/nuvla/job-engine/issues/142)
 - [x] review and adapt job-engine actions (https://github.com/nuvla/job-engine/issues/151)
 - [x] for deployments in pull-mode, the job-engine must setup automatic deployment_updates (https://github.com/nuvla/job-engine/issues/143)
 - [x] update job-distributor-deployment-state to distinguish between push and pull-mode jobs (https://github.com/nuvla/job-engine/issues/155)
 - [x] annotate CRUD and custom actions with capabilities, through metadata (https://github.com/nuvla/api-server/issues/432)
 - [x] when jobs are to be executed in pull-mode, make sure the proper ACLs are set for both the job and target/affected-resources (https://github.com/nuvla/api-server/issues/431)
 - [x] create a Lite mode of the job-engine executor, to run in a NB (https://github.com/nuvla/job-engine/issues/132)
 - [x] when running jobs in pull-mode, start by creating unique lock files per job being executed (https://github.com/nuvla/job-engine/issues/135)
 - [x] add UI changes for supporting the "pull" and "mixed" provisioning mode operations (https://github.com/nuvla/ui/issues/489)
