### ISSUE TITLE
CIMI resource action definition with metadata 

### ISSUE THREAD

**Issue by 0xbase12** [nuvla/nuvla#46]
- [x] Allow to define metadata that describe available resource actions (nuvla/api-server#427)
- [x] Create metadata for existing resources actions  (nuvla/api-server#428)
- [x] Api page action button open modal that allow to give input created from actions metadata (nuvla/ui#502)
- [x] Menubar actions list show available actions depending on resource metadata (nuvla/ui#503)
