### ISSUE TITLE
Bulk action support

### ISSUE THREAD

**Issue by 0xbase12** [nuvla/nuvla#54]
- [x] API-SERVER - Rest API support bulk operations
- [ ] API-SERVER - Resource-metadata contain information on collection support of bulk-actions and give information about needed inputs for each one
- [x] API-SERVER - Deployment resource support bulk-update
- [x] JOB-ENGINE - Implement deployment bulk-update 
- [ ] UI - CIMI API page show available bulk actions in menubar
- [ ] UI - CIMI PAGE allow selecting resources (reuse cimi delete)
- [ ] UI - CIMI PAGE When bulk action is clicked show a modal with needed inputs
- [x] UI - Support selecting with filter or by checkbox on cards or table
- [x] UI - Update specific modal 
- [x] PYTHON-LIBRARY - Support bulk action
- [x] CLOJURE-LIBRARY - Support bulk action
- [ ] ...

**Comment by 0xbase12** [comment]
# API-SERVER - Rest api
PATCH /resource-name/action
Bulk-action authorisation set on resource
bulk header as additionnal protection
Cimi-filter syntax check
Do the query as user and create a job which is visible for the user with affected resources that contains the list of the query with the filter. Limited to 10000.

# Job-engine - Action deployment bulk-update
Job bulk action PARENT

One action per bulk operation
Job PARENT start
create child jobs with the right action on each of target-resource with the payload and same acl as the parent job (using action call on resource? how to set parent of job)
Job PARENT monitor and reports back progress in display-message: agregation of jobs linked to parent by state
WHEN all jobs are done report SUCCESS if any child process finished with success
Job parent Finish

Job PARENT is long running, should support failure in case of api-server restart

# API-SERVER - Deployment update
What parameters for update ?

# Questions
How to make that the user has called the action and not admin from job-engine
Synchronisation 
do we need parent-job nested-jobs ? or we can use parent

**Comment by 0xbase12** [comment]
Bulk operation should have their own resource like deployment-log that allow to not have the parent job in job executor for too long and have just a job distributor to refresh of the execution. This will allow also to have a cancel operation of a bulk operation. For ui, select all is not selecting all items to avoid to manage what should happen if a user unselect one element.
