### ISSUE TITLE
evaluate possibility to display on UI the events & metrics graphs based on historical data in Kafka

### ISSUE THREAD

**Issue by konstan** [nuvla/nuvla#55]
Do this on the example of NB metrics. They are now stored with the metrics collection timestamps in Kafka.

- [ ] validate feasibility to display them on UI using Kafka Streams wrapped for Clojure.
- [ ] select UI graphing library.
- [ ] augment with information from thresholds and alerts as configured by the notification subscriptions and recorded by the streaming platform.

**Comment by konstan** [comment]
@0xbase12 What UI library for producing line plots of time-series would you recommend?
Or I just stick with https://github.com/reactchartjs/react-chartjs-2 which we already use 
https://github.com/nuvla/ui/blob/master/code/src/cljs/sixsq/nuvla/ui/utils/plot.cljs

**Comment by 0xbase12** [comment]
If you have everything you need in chartjs use it: https://www.chartjs.org/samples/latest/
It's better to not have additional deps that will make the nuvla-ui.js production bigger

**Comment by konstan** [comment]
Is my understanding correct that we are actually using https://github.com/reactchartjs/react-chartjs-2, which is a wrapper around chartjs.org. Meaning that the feature set may be reduced: https://www.chartjs.org/samples/latest/ vs https://reactchartjs.github.io/react-chartjs-2/#/ ?

Though, I'm not saying that what is in react-chartjs-2 regarding a simple line-plot is not enough for me.

**Comment by 0xbase12** [comment]
Yes we use react-chartjs2. It contain a subset of all features. If it got what you need it's cool. But if not we still have chartjs dependency required by react-chartjs-2 that contain the full set of chartjs.
