### ISSUE TITLE
Notify customer about end of trial date

### ISSUE THREAD

**Issue by 0xbase12** [nuvla/nuvla#75]
AS A customer with a trialing subscription

I NEED TO be notified about my end of trial date

SO THAT I can add a payment method

**Comment by 0xbase12** [comment]
## Tasks
- [x] https://github.com/nuvla/ui/issues/730
- [x] https://github.com/nuvla/api-server/issues/652
- [x] https://github.com/nuvla/api-server/issues/654
- [x] https://github.com/nuvla/api-server/issues/655
- [x] https://github.com/nuvla/job-engine/issues/231
- [ ] https://github.com/nuvla/api-server/issues/660
- [ ] https://github.com/nuvla/job-engine/issues/230
