### ISSUE TITLE
Nuvla v2.0 general issues

### ISSUE THREAD

**Issue by loomis** [nuvla/nuvla#9]
General:
 
 - [x] #8: packaging decision
 - [x] #7: define release process (depends on #6 and #8)
 - [x] #6: versioning policy
 - [x] #5: reorganize repositories (depends on #6)
 - [x] #3: provide pre-production deployment for nuvla components (depends on #8)
 - [x] #2: build infrastructure migration
 - [x] #1: initial build infrastructure

Moved to later releases:
 - #4: provide developer documentation

**Comment by loomis** [comment]
Removing nuvla/api-server#31.
